### ISSUE TITLE
Make the build of cohod possible without the use of Starport to be able to build it natively on FreeBSD

### ISSUE THREAD

**Issue by Moonshine-cc** [cosmic-horizon/testnets#1]
I have run into issues as our server is powered by FreeBSD instead of Linux.

I was unable to build Starport on FreeBSD, please see [here](https://github.com/tendermint/starport/issues/2042).

However I was able to run the `cohod` Linux binary successfully by making use of the FreeBSD Linux Binary Compatibility layer.

Nonetheless I would prefer to be able to build `cohod` for FreeBSD natively, which should easily be possible considering that golang is available on FreeBSD. In the spirit of cross-plattform-compatibility!

**Comment by bolshoytoster** [comment]
@Moonshine-cc unfortunately, one of the dependencies, [pkg-fetch](https://github.com/vercel/pkg-fetch) doesn't have a BSD release. You could open an issue there if you want.

**Comment by Moonshine-cc** [comment]
> unfortunately, one of the dependencies, [pkg-fetch](https://github.com/vercel/pkg-fetch) doesn't have a BSD release
I'm not sure if that's the issue, as I don't recall any error message concerning pkg-fetch.

But building a Cosmos-SDK project based daemon natively the usual way (without the use of Starport) has never been an issue on FreeBSD so far.

**Comment by bolshoytoster** [comment]
@Moonshine-cc the error `starport/pkg/nodetime/data/data.go:5:9: undefined: binaryCompressed` is caused because `binaryCompressed` is defined in platform specific files. The variable contains the `.tar.gz` of the platform specific executable for nodetime.

The nodetime `.tar.gz` files are generated by the `scripts/nodetime` bash script, this calls `npm i` and `npm run build` in `scripts/data/gen-nodetime`. When I add freebsd to the targets in that `package.json` it gives me an error basically saying it can't fetch a freebsd release of `pkg-fetch`.

> But building a Cosmos-SDK project based daemon natively the usual way (without the use of Starport) has never been an issue on FreeBSD so far.

The error comes from starport so I probably should've replied to your issue there instead of here.

**Comment by Moonshine-cc** [comment]
> The error comes from starport so I probably should've replied to your issue there instead of here

Indeed, that's why I hope that the Coho team will ditch Starport and goes the native build route. But of course this is of no priority, because I can either use the `cohod` or `starport` Linux binary to run natively on FreeBSD and I have already tried both ways successfully.

**Comment by dpdanpittman** [comment]
You can now build cohod from source which should suffice.  Closing this issue.
